[package]
name = "renderer"
edition = "2018"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]

[dependencies]
cgmath = "~0.17.0"
glow = { path = "/home/segfault/Projects/glow" }
glutin = "~0.19.0"
ldraw = { path = "../../ldraw" }
ldraw_renderer = { path = "../../renderer" }