[package]
name = "viewer_native"
edition = "2021"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]

[dependencies]
async-std = "~1.10.0"
cgmath = "~0.18.0"
futures = "~0.3.19"
glow = "~0.11.0"
glutin = "~0.27.0"
ldraw = { path = "../../../ldraw" }
ldraw_ir = { path = "../../../ir" }
ldraw_renderer = { path = "../../../renderer" }
viewer_common = { path = "../common" }
