[package]
name = "ldraw_renderer"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2018"

[dependencies]
approx = "~0.3.1"
cgmath = "~0.17.0"
gl = "~0.11.0"
kdtree = { git = "https://github.com/segfault87/kdtree-rs.git", branch = "nearest_iter_mut" }
ldraw = { path = "../ldraw" }
serde = { version = "1.0", features = ["derive"] }
