[package]
name = "ldraw_renderer"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2018"

[dependencies]
approx = "~0.3.1"
cgmath = "~0.17.0"
# glow = "~0.4.0"
glow = { git = "https://github.com/grovesNL/glow" }
kdtree = "~0.6"
ldraw = { path = "../ldraw" }
serde = { version = "1.0", features = ["derive"] }
