[package]
name = "ldraw"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = { version = "~0.18.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
