[package]
name = "ldraw"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2021"

[dependencies]
cgmath = { version = "~0.18.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
encoding_rs = "~0.8.29"
encoding_rs_io = "~0.1.4"
