[package]
name = "ldr2img"
version = "0.1.0"
edition = "2021"

[dependencies]
"bincode" = "~1.3.3"
"cgmath" = "~0.18.0"
"clap" = "~2.33.3"
"glutin" = "~0.27.0"
"glow" = "~0.11.0"
"image" = "~0.23.14"
"ldraw" = { path = "../../ldraw" }
"ldraw_ir" = { path = "../../ir" }
"ldraw_olr" = { path = "../../olr" }
"ldraw_renderer" = { path = "../../renderer" }
