[package]
name = "baker"
version = "0.1.0"
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2021"

[dependencies]
bincode = "~1.3.3"
cgmath = "~0.18.0"
clap = "~2.33.0"
ldraw = { path = "../../ldraw" }
ldraw_ir = { path = "../../ir" }
serde_json = "~1.0"
